---
- name: Ensure rsync is present
  apt:
   name: rsync
   state: present
   update_cache: yes
  
- name: Copy config files (rsync) for starting rsync daemon
  copy:
   src: rsync
   dest: "{{ rsync_dst }}"
   force: yes
  notify:
  - restart rsync
   
- name: Copy config files (rsyncd.conf) for starting rsync daemon
  copy:
   src: rsyncd.conf
   dest: "{{ rsyncd_dst }}"
   force: yes
  notify:
  - restart rsync
  
- name: Test send file via synchronize
  synchronize:
   mode: push
   dest: "{{ dest_war }}" #on server #need add "dest_war" in default/main.yml
   src: "{{ src_war }}" #on local machine #need add "src_war" in default/main.yml
