---
- name: Ensure rsync is present
  apt:
   name: rsync
   state: present
   update_cache: yes
  
- name: Copy config files (rsync) for starting rsync daemon
  copy:
   src: rsync
   dest: "{{ rsync_dst }}"
   force: yes
  notify:
  - restart rsync
   
- name: Copy config files (rsyncd.conf) for starting rsync daemon
  copy:
   src: rsyncd.conf
   dest: "{{ rsyncd_dst }}"
   force: yes
  notify:
  - restart rsync

- name: Ensure that file for test is created
  file:
   path: /home/1.txt
   state: file
   

- name: Test send file via synchronize
  synchronize:
   mode: push
   dest: "{{ dst_folder }}" #on server #add in default/main.yml
   src: "{{ src_file }}" #on local machine #add in default/main.yml
